### ISSUE TITLE
Docker Runs but after login blank screen

### ISSUE THREAD

**Issue by hakarune** [shlagevuk/docker-hakuneko#6]
Logs just show this repeating over and over:
`Failed to move to new namespace: PID namespaces supported, Network namespace supported, but failed: errno = Operation not permitted`

Here is my docker yml  file
```
 hakuneko:
    image: shlagevuk/hakuneko
    network_mode: bridge
    container_name: hakuneko
    volumes:
        - /sharedfolders/Alt_External/docker_configs/hakuneko:/config
        - /sharedfolders/Veritas/Manga:/manga 
    ports:
        - 5003:8080
    environment:
        - PUID=1000
        - PGID=100
        - TZ=America/Los_Angeles
        - VIRTUAL_HOST=hakuneko.local
        - VIRTUAL_PORT=5003
        - GUAC_USER=admin #optional
        - GUAC_PASS=
        - cap-add=SYS_ADMIN
    restart: unless-stopped
```

tried different configs, but same error each time
